server:
  port: 8080

spring:
  #security:
  #  user:
  #    name: user
  #    password: pass
  datasource:
    url: jdbc:mysql://localhost:3306/blogdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true